# Generated by Django 5.1.5 on 2025-02-02 00:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superfoods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_c', models.CharField(max_length=100)),
                ('description_c', models.TextField()),
                ('image_c', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_m', models.CharField(max_length=100)),
                ('description_m', models.TextField()),
                ('image_m', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superfoods.categories_2')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superfoods.manufacturers_2')),
            ],
        ),
    ]
