# Generated by Django 5.1.5 on 2025-02-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superfoods', '0002_categories_2_manufacturers_2_products_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
