# Generated by Django 5.1.5 on 2025-02-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superfoods', '0003_remove_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_2',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products_2',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Categories_2',
        ),
        migrations.DeleteModel(
            name='Manufacturers_2',
        ),
        migrations.DeleteModel(
            name='Products_2',
        ),
    ]
